### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by Estigy** [wirecard/checkout-client-library#1]
Hi.

I just wanted to ask what the current status of this project is. Since it has gone online just a few days ago, is this already usable for production?
And is this the official client code from the Wirecard company, or is this a private project?

Thanks, Estigy.

**Comment by JuEger** [comment]
Hi Estigy,

currently this project is used by our team as a base for all PHP based Checkout page and Checkout seamless shop plugins. It already exists internally for some years and therefor is stable.
Right now we can't give official support for it because it's only meant to be used by our team internal plugin developers. However, if you find any issues we are more then willing to help resolving them, if the development team has enough time for it.

best Regards
Juergen Eger

**Comment by Estigy** [comment]
Hi, Jürgen.
Thanks for this very fast (!) response.
Do you have any kind of documentation on this toolbox?

I'm currently going with https://github.com/hochstrasserio/wirecard, but I'm right at the beginning and would prefer using an official library, of course.

**Comment by JuEger** [comment]
Hi Estigy,

currently we do not have (beside the auto-generatable phpdoc) a documentation for this library, but we are planing on redesigning and opening it up for external use also. 
Then there will also be official support and a documentation on github. But before that we are planing a refactoring of the library.

best Regards
Juergen Eger
